Isaiah fowler
BloomTech-Labs/deprecated-labs31-family-promise-spokane-be-a pull request #12
Opened 2020-12-21 18:58 UTC by isaiah-j

# PR Description
​
- Fixed bug inside the notes router​
- Added "shareable" flag to the notes model
- Created route inside families router that sends back all notes related to that family
- Guests are restricted to only viewing shareable notes
​
## Type of Change
​
Types of Change:
- [] New feature
- [] Refactoring / Bug fix 
​

## Testing
​
- [] No​
​
## Completeness
Is this feature complete
- [] Feature Complete

​

2020-12-21 23:49 UTC, rleslie1015 requested changes
Awesome job! Please review my comments about the commented out code and I will approve!

2020-12-21 23:49 UTC, rleslie1015 commented on api/families/familiesModel.js
> +};
Awesome thanks for adding the restriction here of notes that guests should not be able to view! I was wondering how to do this and you did it super clean and concise. BRAVO

2020-12-21 23:49 UTC, rleslie1015 commented on api/families/familiesModel.js
> +const findAllNotesByFamilyId = async (id, role) => {
Why is there an `async` keyword but no `await`?

2020-12-21 23:49 UTC, rleslie1015 commented on api/families/familiesRouter.js
> +  const { role } = req.user;
Nice, I didn't think of putting a notes endpoint by family but this is def helpful!

2020-12-21 23:49 UTC, rleslie1015 commented on data/migrations/20201209161927_notes.js
> +    tbl.date('date').defaultTo(knex.fn.now())
Love this. I didn't know Knex had this functionality.

2020-12-21 23:49 UTC, rleslie1015 commented on api/notes/notesRouter.js
> +  const queries = { ...req.query };
Does `req.query` return notes based on the URL or request body or both?

2020-12-21 23:49 UTC, rleslie1015 commented on api/notes/notesRouter.js
>  // checkRole.grantAccess('readOwn', 'notes'),
Can we remove this commented out code? If this is documentation it should be clear

2020-12-21 23:49 UTC, rleslie1015 commented on api/notes/notesRouter.js
> -  Notes.findById(family_id)
NICE CATCH thanks for fixing this!

2020-12-21 23:49 UTC, rleslie1015 commented on api/notes/notesRouter.js
> +      res.status(204).json({ message: 'deleted' });
Beautiful refactoring.

2020-12-21 23:57 UTC, isaiah-j commented on api/families/familiesModel.js
> +const findAllNotesByFamilyId = async (id, role) => {
whoops nice catch. We can remove that

2020-12-21 23:58 UTC, rleslie1015 commented on api/families/familiesModel.js
> +const findAllNotesByFamilyId = async (id, role) => {
sweet!

2020-12-22 00:04 UTC, abdimohamud commented
looks great to me! will make sure to add new endpoint to API docs, but if we dont need to change the seeds for the date fix, then its good to migrate and re-deploy the db!

2020-12-22 00:11 UTC, isaiah-j commented on api/notes/notesRouter.js
>  // checkRole.grantAccess('readOwn', 'notes'),
Sure thing

2020-12-22 00:11 UTC, rleslie1015 approved these changes

2020-12-22 00:14 UTC, abdimohamud approved these changes

2020-12-22 00:14 UTC, merged